apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  template:
    spec:
      containers:
      - name: mysql
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1Gi